# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20171002_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='job',
            name='req_deg',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='req_major',
            field=models.CharField(max_length=30),
        ),
    ]
