# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 16:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20171008_2217'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='job_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='candidates',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
