# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 17:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20171008_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidates',
            name='status',
            field=models.CharField(default=b'Waiting', max_length=20),
        ),
    ]
